inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

require:
  - rubocop-performance
  - rubocop-md
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

# Enforcing double quotes.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true

# Most readable form.
Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

# Check with yard instead.
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 250

RSpec/ExampleLength:
  Max: 7

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/SubjectStub:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 100

Metrics/ParameterLists:
  Max: 30

Metrics/ClassLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/AbcSize:
  Max: 30
